### ISSUE TITLE
Add array_value node type

### ISSUE THREAD

**Issue by lukepur** [lukepur/data-workflow-engine#2]
It should be possible to specify a `value` node as an array of values so that:

1. Array level validations can be specified (e.g. array must contain at least 2 items)
2. Element level validations can be specified (e.g. each item must be a number)

An example configuration might look like:
```
- id: contact_numbers
  type: array_value
  validations:
  - fn: greaterThan
    args:
    - fn: arrayLength
      args: 
      - $value
    - 2
    message: At least 2 contact numbers are required
  item_validations:
  - fn: isNumeric
     args:
     - $value
     message: Contact numbers must be numeric
```
