### ISSUE TITLE
Add `fnRef` as resolvable type

### ISSUE THREAD

**Issue by lukepur** [lukepur/data-workflow-engine#4]
An `fnRef` resolvable type allows pointing to a context method directly, rather than trying to resolve the result of that function. An example of where this would be useful is when a `reduce` fn needs a function reference, rather than the result of running the function in the execution context:

```
derived:
- id: sum
  fn: reduce
  args:
  - $.pathTo.anArray.*
  - fnRef: sum # context has function sum(a, b) { return a + b;}
  - 0
```

Additionally, an `fnRef`'s value itself should be resolvable, therefore allowing advanced usage such as higher order functions returning primed worker functions.
